export class EventType {
    static NEW_VIEW = 'newViewEvent';
    static RENAME_ARTEFACT = 'renameArtefact';
    static PROJECT_LOADED = 'projectLoaded';
    static DECISON_DELETED = 'decisonDeleted';
    static OPEN_SEARCH = 'openSearch';
    static DATA_CHANGED = 'dataChanged';
    static IMPORT_DATA = 'importData';
    static EXPORT = 'export';
    static JUMP_TO_TEST = 'jumpToTest';
    static FOLDER_CHANGED = 'folderChanged';
    static OPENED_FILE_CHANGED = 'openedFileChanged';
    static REFRESH_WORKSPACE = 'refreshWorkspace';
    static JUMP_TO_TAB = 'jumpToTab';
    static GITERROR = 'giterror';
    static TEXT_REPLACED = 'textReplaced';
    static COPY_RULES = 'copyRules';
    static PASTE_RULES = 'pasteRules';
}
